version: '3.8'

services:

  nginx:
    image: nginx:1.27
    container_name: ecomm_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orders_srv
      - users_srv
      - products_srv

  orders_srv:
    build: ./orders
    container_name: ecomm_orders_srv
    ports:
      - "8003:8003"
    env_file: ./orders/.docker.env

  users_srv:
    build: ./users
    container_name: ecomm_users_srv
    ports:
      - "8001:8001"
    env_file: ./users/.docker.env

  products_srv:
    build: ./products
    container_name: ecomm_products_srv
    ports:
      - "8002:8002"
    env_file: ./products/.docker.env
