version: '3.8'

services:

  swagger:
    image: swaggerapi/swagger-ui:v5.17.14
    container_name: ecomm_swagger_ui
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      SWAGGER_JSON: /usr/share/nginx/openapi.yaml
    volumes:
      - ./nginx/nginx-swg.conf:/etc/nginx/conf.d/ecommerce.conf:ro
      - ./swagger/ecommerce.yaml:/usr/share/nginx/openapi.yaml
    depends_on:
      - orders_srv
      - users_srv
      - products_srv

  orders_srv:
    build: ./orders
    container_name: ecomm_orders_srv
    ports:
      - "8003:8003"
    env_file: ./orders/.docker.env

  users_srv:
    build: ./users
    container_name: ecomm_users_srv
    ports:
      - "8001:8001"
    env_file: ./users/.docker.env

  products_srv:
    build: ./products
    container_name: ecomm_products_srv
    ports:
      - "8002:8002"
    env_file: ./products/.docker.env
